version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.6-browsers
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install -s ~/build/.circleci/settings.xml

workflows:
  build_and_test:
    jobs:
      - build
